services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      - REDIS_URL=redis://host.docker.internal:6379
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./web
    ports:
      - "3000:80"
    depends_on:
      - backend
